service: scrape-the-news
app: scrapethenews
org: miksimal

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
        - comprehend:DetectSentiment
        - lambda:InvokeFunction
      Resource: '*'

# TODO: don't give lazy access to all resources like the above

functions:
  bbcScraper:
    handler: handler.bbcScraper
    events:
      - schedule:
          name: bbc-invoke-every-day-at-10am
          description: 'invokes the scraper lambda every day at 10am UTC'
          rate: cron(0 10 * * ? *)
    environment:
      BBC_HEADLINES_TABLE: bbcHeadlines
  getLatestBbc:
    handler: api.getLatestBbc
    events:
      - http:
          path: getlatestbbc
          method: get
          cors: true
    environment:
      BBC_HEADLINES_TABLE: bbcHeadlines
  analyser:
    handler: analysisHandler.analyser
    runtime: python3.6

resources:
  Resources:
    bbcHeadlinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bbcHeadlines
        AttributeDefinitions:
          - AttributeName: year
            AttributeType: N
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: year
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
