# Welcome to Serverless!
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: scrape-the-news
app: scrapethenews
org: miksimal

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
        - comprehend:DetectSentiment
        - lambda:InvokeFunction
      Resource: '*'
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  scraper:
    handler: handler.scraper
    events:
      - schedule:
          name: invoke-every-day-at-10am
          description: 'invokes the scraper lambda every day at 10am UTC'
          rate: cron(0 10 * * ? *)
    environment:
      HEADLINES_TABLE: headlines
  bbcScraper:
    handler: handler.bbcScraper
    events:
      - schedule:
          name: bbc-invoke-every-day-at-10am
          description: 'invokes the scraper lambda every day at 10am UTC'
          rate: cron(0 10 * * ? *)
    environment:
      BBC_HEADLINES_TABLE: bbcHeadlines
  getLatest:
    handler: api.getLatest
    events:
      - http:
          path: getlatest
          method: get
          cors: true
    environment:
      HEADLINES_TABLE: headlines
  getLatestBbc:
    handler: api.getLatestBbc
    events:
      - http:
          path: getlatestbbc
          method: get
          cors: true
    environment:
      BBC_HEADLINES_TABLE: bbcHeadlines
  analyser:
    handler: analysisHandler.analyser
    runtime: python3.6

resources:
  Resources:
    topHeadlinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: topHeadlines
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    headlinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: headlines
        AttributeDefinitions:
          - AttributeName: year
            AttributeType: N
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: year
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    bbcHeadlinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bbcHeadlines
        AttributeDefinitions:
          - AttributeName: year
            AttributeType: N
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: year
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
